using System;
using System.IO;
using System.Text;
using System.Collections.Generic;

class Program
{
    static void Main()
    {
        string filePath = @"C:\Users\ishan\Documents\Projects\Robotic-Arm-Mini\firmware\robotic-arm-mini-core-fw\Robot\actuators\mintasca\sca_api.c";
        string content = File.ReadAllText(filePath, Encoding.UTF8);

        var replacements = new Dictionary<string, string>
        {
            {"位置值", "position value"},
            {"，快速", ", fast"},
            {"更新至句柄中", "update to handle"},
            {"要操作的Actuator 句柄地址或指针", "handle address or pointer of actuator to operate"},
            {"要操作的Actuator 句柄指针或地址", "handle address or pointer of actuator to operate"},
            {"清空status位", "Clear status bit"},
            {"目标position loop", "Target position loop"},
            {"Kp值，实际值", "Kp value, real value"},
            {"Ki值，实际值", "Ki value, real value"},
            {"获取Actuator", "Get Actuator"},
            {"输出上限，real value", "output upper limit, real value"},
            {"输出下限，real value", "output lower limit, real value"},
            {"输出上限", "output upper limit"},
            {"输出下限", "output lower limit"},
            {"偏置值，实际值", "offset value, real value"},
            {"偏置值", "offset value"},
            {"最大值", "max value"},
            {"最小值", "min value"},
            {"位置极限status", "position limit status"},
            {"滤波器status", "filter status"},
            {"带宽值，实际值", "bandwidth value, real value"},
            {"带宽值", "bandwidth value"},
            {"速度值", "velocity value"},
            {"目标velocity loop", "Target velocity loop"},
            {"电流值", "current value"},
            {"目标current loop", "Target current loop"},
            {"，以mA为单位", ", in mA"},
            {"等待", "wait for "},
            {"成功", "success"},
            {"失败", "fail"},
            {"执行", "execute "},
            {"读出", "read out "},
            {"缓存", "cache"},
            {"写入", "write in "},
            {"查询", "query "},
            {"超时", "timeout"},
            {"保护", "protection "},
            {"温度值", "temperature value"},
            {"电压值", "voltage value"},
            {"无", "None"},
            {"等", "etc."},
            {"该", "the "},
            {"且", "and "},
            {"或", "or "},
            {"返回", "return "},
            {"如果", "if "},
            {"否则", "else "},
            {"则", "then "},
            {"的", " of "},
            {"需要", "need "},
            {"时", " when "},
            {"在", " at "},
            {"从", " from "},
            {"到", " to "},
            {"将", " will "},
            {"用于", " used for "},
            {"使用", " use "},
            {"并", " and "},
            {"并且", " and "},
            {"可以", " can "},
            {"但是", " but "},
            {"不能", " cannot "},
            {"会", " will "},
            {"被", " be "},
            {"已经", " already "},
            {"目前", " currently "},
            {"全部", " all "},
            {"任何", " any "},
            {"不同", " different "},
            {"相同", " same "},
            {"因为", " because "},
            {"所以", " so "},
            {"为了", " in order to "},
            {"即使", " even if "},
            {"只有", " only "},
            {"只要", " as long as "},
            {"一直", " always "},
            {"停止", " stop "},
            {"开始", " start "},
            {"结束", " end "},
            {"初始化", " initialize "},
            {"配置", " configure "},
            {"参数", " parameter "},
            {"信息", " information "},
            {"数据", " data "},
            {"状态", " status "},
            {"模式", " mode "},
            {"设备", " device "},
            {"节点", " node "},
            {"网络", " network "},
            {"总线", " bus "},
            {"通信", " communication "},
            {"协议", " protocol "},
            {"指令", " command "},
            {"帧", " frame "},
            {"有效", " valid "},
            {"无效", " invalid "},
            {"打开", " open "},
            {"关闭", " close "},
            {"复位", " reset "},
            {"默认", " default "},
            {"用户", " user "},
            {"系统", " system "},
            {"错误", " error "},
            {"正常", " normal "},
            {"异常", " abnormal "},
            {"发生", " occur "},
            {"处理", " process "},
            {"更新", " update "},
            {"存储", " save "},
            {"清空", " clear "},
            {"保留", " keep "},
            {"占用", " occupy "},
            {"释放", " release "},
            {"分配", " allocate "},
            {"创建", " create "},
            {"销毁", " destroy "},
            {"增加", " increase "},
            {"减少", " decrease "},
            {"修改", " modify "},
            {"查看", " view "},
            {"控制", " control "},
            {"计算", " calculate "},
            {"判断", " judge "},
            {"比较", " compare "},
            {"检查", " check "},
            {"测试", " test "},
            {"实际值", "real value"},
            {"上限", "upper limit"},
            {"下限", "lower limit"},
            {"目标", "target "},
            {"发送", "send "},
            {"接收", "receive "},
            {"完成", "finish "},
            {"退出", "exit "},
            {"进入", "enter "},
            {"切换", "switch "},
            {"延时", "delay "},
            {"防止", "prevent "},
            {"过载", "overload "},
            {"标志位", "flag bit "},
            {"函数", "function "},
            {"直接", "directly "},
            {"寄存器", "register "}
        };

        foreach (var kvp in replacements)
        {
            content = content.Replace(kvp.Key, kvp.Value);
        }

        // Clean up some odd spaces created by simple translation
        content = content.Replace("  ", " ");
        
        File.WriteAllText(filePath, content, new UTF8Encoding(false));
    }
}
